groups:
- name: nginx_alerts
  rules:
  - alert: HighRequestRate
    expr: sum(rate(nginx_http_requests_total[1m])) > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Alerta: Alto tr치fico en Nginx"
      description: "La tasa de solicitudes ha superado 100 por segundo durante m치s de 5 minutos."

  - alert: HighNginxTraffic
    expr: nginx_traffic_requests > 1
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Tr치fico alto en Nginx"
      description: "El tr치fico en Nginx es mayor a 100 solicitudes por minuto en {{ $labels.instance }}"
