prometheus:
  container_name: prometheus
  ports:
    - 9090:9090
  volumes:
    - ./:/etc/prometheus
  image: prom/prometheus

alertmanager:
   image: prom/alertmanager
   ports:
     - 9093:9093
   volumes:
     - ./:/etc/alertmanager
